export const keyItemCategories = [
  { id: "all", label: "All Key Items" },
  { id: "Skandha", label: "Skandhas" },
  { id: "Relic", label: "Relics" },
  { id: "Essence", label: "Essences" },
  { id: "Quest Item", label: "Quest Items" },
  { id: "Captain Spirit", label: "Captain Spirits" },
];

export const keyItemsData = [
  {
    id: "skandha-of-form",
    slug: "skandha-of-form",
    name: "Skandha of Form",
    category: "Skandha",
    symbol: "蕴",
    image: `/images/items/key-items/skandha-of-form.png`,
    description: "A sacred relic associated with physical form and one of the five Skandhas.",
    number: 1,
  },
  {
    id: "buddha's-eyeball",
    slug: "buddha's-eyeball",
    name: "Buddha's Eyeball",
    category: "Relic",
    symbol: "遗",
    image: `/images/items/key-items/buddha's-eyeball.png`,
    description: "A mysterious stone eye carrying traces of ancient spiritual power.",
    number: 2,
  },
  {
    id: "keeness-of-tiger",
    slug: "keeness-of-tiger",
    name: "Keenness of Tiger",
    category: "Relic",
    symbol: "遗",
    image: `/images/items/key-items/keeness-of-tiger.png`,
    description: "A forceful relic embodying the sharp instinct and ferocity of a tiger.",
    number: 3,
  },
  {
    id: "sterness-of-stone",
    slug: "sterness-of-stone",
    name: "Sterness of Stone",
    category: "Relic",
    symbol: "遗",
    image: `/images/items/key-items/sterness-of-stone.png`,
    description: "A hardened essence reflecting the unyielding nature of stone.",
    number: 4,
  },
  {
    id: "stone-essence",
    slug: "stone-essence",
    name: "Stone Essence",
    category: "Essence",
    symbol: "精",
    image: `/images/items/key-items/stone-essence.png`,
    description: "Condensed mineral essence gathered from a powerful stone being.",
    number: 5,
  },
  {
    id: "skandha-of-feeling",
    slug: "skandha-of-feeling",
    name: "Skandha of Feeling",
    category: "Skandha",
    symbol: "蕴",
    image: `/images/items/key-items/skandha-of-feeling.png`,
    description: "A sacred relic connected to sensation, emotion and perception.",
    number: 6,
  },
  {
    id: "sobering-stone",
    slug: "sobering-stone",
    name: "Sobering Stone",
    category: "Quest Item",
    symbol: "钥",
    image: `/images/items/key-items/sobering-stone.png`,
    description: "A peculiar stone used to awaken clarity and dispel drunken confusion.",
    number: 7,
  },
  {
    id: "pungent-flesh-chunk",
    slug: "pungent-flesh-chunk",
    name: "Pungent Flesh Chunk",
    category: "Quest Item",
    symbol: "钥",
    image: `/images/items/key-items/pungent-flesh-chunk.png`,
    description: "A foul-smelling piece of flesh required for a special encounter.",
    number: 8,
  },
  {
    id: "loong-scales",
    slug: "loong-scales",
    name: "Loong Scales",
    category: "Relic",
    symbol: "遗",
    image: `/images/items/key-items/loong-scales.png`,
    description: "Ancient scales that resonate with the hidden power of the Loongs.",
    number: 9,
  },
  {
    id: "old-rattle-drum",
    slug: "old-rattle-drum",
    name: "Old Rattle-Drum",
    category: "Quest Item",
    symbol: "钥",
    image: `/images/items/key-items/old-rattle-drum.png`,
    description: "A worn rattle-drum whose sound recalls a forgotten childlike memory.",
    number: 10,
  },
  {
    id: "arhat-gold-piece",
    slug: "arhat-gold-piece",
    name: "Arhat Gold Piece",
    category: "Relic",
    symbol: "遗",
    image: `/images/items/key-items/arhat-gold-piece.png`,
    description: "A golden fragment carrying the solemn aura of an Arhat.",
    number: 11,
  },
  {
    id: "skandha-of-thought",
    slug: "skandha-of-thought",
    name: "Skandha of Thought",
    category: "Skandha",
    symbol: "蕴",
    image: `/images/items/key-items/skandha-of-thought.png`,
    description: "A sacred relic representing recognition, conception and thought.",
    number: 12,
  },
  {
    id: "special-made-bone-strengthening-pellet",
    slug: "special-made-bone-strengthening-pellet",
    name: "Special-Made Bone-Strengthening Pellet",
    category: "Quest Item",
    symbol: "钥",
    image: `/images/items/key-items/special-made-bone-strengthening-pellet.png`,
    description: "A specially prepared pellet connected to a hidden request.",
    number: 13,
  },
  {
    id: "the-spirit-of-captain-kalpa-wave",
    slug: "the-spirit-of-captain-kalpa-wave",
    name: "The Spirit of Captain Kalpa-Wave",
    category: "Captain Spirit",
    symbol: "魂",
    image: `/images/items/key-items/the-spirit-of-captain-kalpa-wave.png`,
    description: "The preserved spirit left behind by Captain Kalpa-Wave.",
    number: 14,
  },
  {
    id: "the-spirit-of-captain-lotus-vision",
    slug: "the-spirit-of-captain-lotus-vision",
    name: "The Spirit of Captain Lotus-Vision",
    category: "Captain Spirit",
    symbol: "魂",
    image: `/images/items/key-items/the-spirit-of-captain-lotus-vision.png`,
    description: "The lingering spirit of Captain Lotus-Vision.",
    number: 15,
  },
  {
    id: "the-spirit-of-captain-void-illusion",
    slug: "the-spirit-of-captain-void-illusion",
    name: "The Spirit of Captain Void-Illusion",
    category: "Captain Spirit",
    symbol: "魂",
    image: `/images/items/key-items/the-spirit-of-captain-void-illusion.png`,
    description: "The remaining essence of Captain Void-Illusion.",
    number: 16,
  },
  {
    id: "the-spirit-of-captain-wise-voice",
    slug: "the-spirit-of-captain-wise-voice",
    name: "The Spirit of Captain Wise-Voice",
    category: "Captain Spirit",
    symbol: "魂",
    image: `/images/items/key-items/the-spirit-of-captain-wise-voice.png`,
    description: "The captured spirit of Captain Wise-Voice.",
    number: 17,
  },
  {
    id: "violet-hail",
    slug: "violet-hail",
    name: "Violet Hail",
    category: "Quest Item",
    symbol: "钥",
    image: `/images/items/key-items/violet-hail.png`,
    description: "A strange purple object with a sinister and transformative aura.",
    number: 18,
  },
  {
    id: "proto-amourworm",
    slug: "proto-amourworm",
    name: "Proto-Amourworm",
    category: "Quest Item",
    symbol: "钥",
    image: `/images/items/key-items/proto-amourworm.png`,
    description: "An immature creature required for a secret progression path.",
    number: 19,
  },
  {
    id: "rice-cocoons",
    slug: "rice-cocoons",
    name: "Rice Cocoons",
    category: "Quest Item",
    symbol: "钥",
    image: `/images/items/key-items/rice-cocoons.png`,
    description: "Pale cocoons gathered as food for a developing creature.",
    number: 20,
  },
  {
    id: "blood-stained-needle",
    slug: "blood-stained-needle",
    name: "Blood-Stained Needle",
    category: "Relic",
    symbol: "遗",
    image: `/images/items/key-items/blood-stained-needle.png`,
    description: "A crimson-stained needle linked to a concealed and dangerous foe.",
    number: 21,
  },
  {
    id: "past-echo",
    slug: "past-echo",
    name: "Past-Echo",
    category: "Relic",
    symbol: "遗",
    image: `/images/items/key-items/past-echo.png`,
    description: "A remnant through which fragments of the past continue to reverberate.",
    number: 22,
  },
  {
    id: "skandha-of-choice",
    slug: "skandha-of-choice",
    name: "Skandha of Choice",
    category: "Skandha",
    symbol: "蕴",
    image: `/images/items/key-items/skandha-of-choice.png`,
    description: "A sacred relic tied to intention, action and volition.",
    number: 23,
  },
  {
    id: "skandha-of-consciousness",
    slug: "skandha-of-consciousness",
    name: "Skandha of Consciousness",
    category: "Skandha",
    symbol: "蕴",
    image: `/images/items/key-items/skandha-of-consciousness.png`,
    description: "A sacred relic associated with awareness and the final Skandha.",
    number: 24,
  }
];

export default keyItemsData;
